// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
namespace BasketballScores
{
    public partial class DefaultPage
    {
        protected global::System.Web.UI.WebControls.Literal litGames;
        protected global::System.Web.UI.WebControls.Literal litWins;
        protected global::System.Web.UI.WebControls.Literal litLosses;
        protected global::System.Web.UI.WebControls.Literal litDraws;
        protected global::System.Web.UI.WebControls.Literal litPlayers;
        protected global::System.Web.UI.WebControls.Repeater rptRecentGames;
        protected global::System.Web.UI.WebControls.Label lblNoGames;
        protected global::System.Web.UI.WebControls.Repeater rptTopScorers;
        protected global::System.Web.UI.WebControls.Label lblNoPlayers;
    }
}