// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
namespace BasketballScores
{
    public partial class GameDetailPage
    {
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litSubtitle;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.TextBox txtDate;
        protected global::System.Web.UI.WebControls.TextBox txtOpponent;
        protected global::System.Web.UI.WebControls.TextBox txtLocation;
        protected global::System.Web.UI.WebControls.TextBox txtOurScore;
        protected global::System.Web.UI.WebControls.TextBox txtOpponentScore;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.TextBox txtNotes;
        protected global::System.Web.UI.WebControls.HiddenField hfGameId;
        protected global::System.Web.UI.WebControls.Button btnUpdateGame;
        protected global::System.Web.UI.WebControls.Panel pnlNoPlayers;
        protected global::System.Web.UI.WebControls.Panel pnlStats;
        protected global::System.Web.UI.WebControls.Repeater rptStats;
        protected global::System.Web.UI.WebControls.Button btnSaveStats;
    }
}