// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
namespace BasketballScores
{
    public partial class PlayersPage
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Literal litFormTitle;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.TextBox txtJersey;
        protected global::System.Web.UI.WebControls.DropDownList ddlPosition;
        protected global::System.Web.UI.WebControls.HiddenField hfEditId;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Repeater rptPlayers;
        protected global::System.Web.UI.WebControls.Label lblNoPlayers;
        protected global::System.Web.UI.WebControls.Literal litFormTitle2;
        protected global::System.Web.UI.WebControls.Label lblNoPlayers2;
        protected global::System.Web.UI.WebControls.Label lblMessage2;
    }
}